{% set pkgname = "pyhocon" %}
{% set version = "0.3.35" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a250806382e9408958449d0bc79ef7caa1bc5220bc29bfc7b79556fe767833b6" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: '{{ pkgname }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyhocon=pyhocon.tool:main

requirements:
  build:
    - pip
    - python
    - pyparsing >=2.0.3

  run:
    - python
    - pyparsing >=2.0.3

test:
  imports:
    - pyhocon

  commands:
    - pyhocon --help

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache-2.0
  license_family: APACHE
  summary: 'HOCON parser for Python'
  description: 'HOCON parser for Python'
  doc_url: https://pythonhosted.org/pyhocon/
  dev_url: http://github.com/chimpler/pyhocon/

extra:
  recipe-maintainers:
    - nelson-liu
    - shahin
