{% set pkgname = "pyhocon" %}
{% set version = "0.3.57" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: 6d6697bf3bfceb50b71fe5f8e29391c42ba727ff032f66208bf7711367e20161

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyhocon=pyhocon.tool:main

requirements:
  build:
    - pip
    - python
    - pyparsing >=2.0.3
    - asset
    - setuptools

  run:
    - python
    - pyparsing >=2.0.3
    - asset
    - setuptools

test:
  imports:
    - pyhocon

  commands:
    - pyhocon --help

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HOCON parser for Python
  description: HOCON parser for Python
  doc_url: https://pythonhosted.org/pyhocon/
  dev_url: http://github.com/chimpler/pyhocon/

extra:
  recipe-maintainers:
    - nelson-liu
    - shahin
