travis:
  secure:
    BINSTAR_TOKEN: FMJjd3+4l7KUTzdceSqNycqbhN8ESA4PKlITxLtFgDQjPK+6/C3gwAH6ThtYRq//mC+aFOw06gF+n4E0sJ4Cb2Z0za3+gkqbnRfxhSw/5oTpU8LB27JkLQDLhehXN5x4xZB5eNeElsPHkOO+6SoH9jOA85gPOF/bO0eRg4igtmCoQo3MJgE4cLiMLpLpOiVLm6Glo86EglQQ5XV6bnQ1rvMykiM57E6KA8JLxvgqN/cPUbKpmX1VCjeFr04dMAVlMwRU4ZhLAOHBCd7CXNgt6yvx76fiazi/RbxbhFZ+AY7jrNGBuKwwjGoSGz7K13BkrVB3NxYYbH6y5KVK9VqfvAbbULfGPqSAisHtDGSPgQ3bCZcvASJr/3fhMeVgZ/2pLBafMt1rs+4uOSQ0DxMAMaQNVU8V/sZf4qVakYG7W/RLtCRw7rC7JK7JVQ2Hu3budwFlZDDIxui4x3itJQoIhgh7RVwH3G8IQGwu9vN10hXTrGhiuU4S7H/0H776EW1pNK03hWTWX3KEE7nvCd3d2I3b2lKAIeK2r7C2v3de5Pz+nXFPYtEVcNiN6wME0XvBUM1if7iVVrS5AVaWu5mTF+OPRI+IqBaRZFswN3x7STANaRliUoHhtwvCyNDQqEq6CqRBlb23TaNS6K6aVtCLRz5t3x1w4J+Qe1oCsohwlIY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
