travis:
  secure:
    BINSTAR_TOKEN: zt8+D6CpA9tvJHu6kHsMgBciQdcrFz0hzSY9xWDRioJLet149zCHMFIkg/dvN5XpTNxSwT3dyEPIiT6tnYWf951rRyGFIAoPPESke1Lb8GGmsIiIUDhx+4qOe0ymey4182V4SotNPUsLMev684J17Nsf00BzmmU/UUuAzYt3RRURX6h5HJ67oBVjV7MZ0nuDor0KM/BYP5SwdV/xB+WKRbJOQeKzP4ZT7Pol904sEpPvWog9SbfAIrs53o48IpP2sJSOZhVYJAbEGy9hfTcfe73/40+LmSeLNAWwxU1AnPDV+R1e9LxssqR5hwQr8Tv2fzqNvl0D96tQqVkfbmjrWCHf5HQUzfbTYilTN9N6Q6Y03chLvT6gPp13hJkKne3DeAMrh2RCu0LuU05m9XuYRL6sNlWz+zxdMWTFoBIhaJA14MUnmRbbRhk/lb/NrevAdmM1M7ohPntsz29002oqCNRLRNFP3FZ1cijAbT1biiSzX+e1M+v93qESByCxjRVkwSM5Q74P0kDxnro8kSjAaalOx84fn7d/ZhVqUCXr1YZLU5X4h1XdAQ7GohV00Zq3UPrNXKcTEUJWCXsfmrv08l+cF6kToRvB111WJObHazTalgAWaZrospK4Kbmu0uksb0wkKkf4GXUpuV7JghjMnqjzIYRnDcN3gYK5N2RHDCc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
